name: diary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0 
  path: ^1.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
